apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kik
  namespace: kik
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kik
    spec:
      containers:
      - name: kik
        image: aliayubkhan/susi_kikbot:latest
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        env:
        - name: API_KEY
          value: "bd4e1bb8-af35-4f3e-a7ca-8c35199145cb"
        - name: BASE_URL
          value: "https://susi-kikbot.tk/"
        ports:
        - containerPort: 8080
