apiVersion: extensions/v1beta1
kind: kik
metadata:
  name: kik
  namespace: kik
  annotations:
    # kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  # tls:
  # - hosts:
  #   - echo.example.com
  #   secretName: echoserver-tls
  rules:
  - host: susi-kikbot.tk
    http:
      paths:
      - path: /
        backend:
          serviceName: kik
          servicePort: 80
